[project]
name = "stock-analyzer"
version = "0.1.0"
description = "Stock Analyzer"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.3.3",
    "pre-commit>=4.3.0",
    "requests>=2.32.5",
    "ruff>=0.14.4",
    "yfinance>=0.2.66",
]
